### ISSUE TITLE
Turn Channels

### ISSUE THREAD

**Issue by drewda** [opentraffic/osmlr#12]
from @dnesbitt61:

![osmlr edge cases - google docs 2017-02-09 10-53-15](https://cloud.githubusercontent.com/assets/212369/22798217/f713769c-eeb5-11e6-9aa7-9d7b9601828b.png)

Turn channels or turn lanes are short (maximum length = TBD) edges that allow turns to bypass the intersection of 2 edges. 

Proposal:

Do the following rather than creating separate OSMLR segments for the turn lane edge and the 2 short edges between the turn lane endpoints and the intersection:

- Extend the OSMLR segments to the intersection (e.g., bypass nodes that only connect to turn channels).
- In valhalla_associate_segments create traffic chunks that associate the turn channel to each of the 2 “internal” edges.

The goal would be to associate a trace along Snowden River Pkwy through the turn channel onto Waterloo Rd would “end” the OSMLR segment along Snowden River Pkwy and begin the segment along Waterloo Rd.

**Comment by drewda** [comment]
from @zerebubuth:

> would “end” the OSMLR segment along Snowden River Pkwy and begin the segment along Waterloo Rd

The disadvantage is loss of precision. Having 2 segments to associate data to, rather than 3, means we lose the extra "dimension" to express traffic conditions on the link. Instead, traffic on the link (which may not affect traffic on either road it's connected to) will be assigned to one road or the other, or a mixture of the two. This may be an acceptable loss of precision.

**Comment by dnesbitt61** [comment]
Current code is not adding turn channels as OSMLR segments and is allowing merging across intersections with a turn channel - so that OSMLR segments continue to the true intersection. One step remains - we should add a special step to the Valhalla edge association logic to match a turn channel to the "intersecting" OSMLR segments so that map-matching correctly terminates segments that match to turn channels.

**Comment by dnesbitt61** [comment]
This should be handled in the updated intersection transition logic. The time/distance from OSMLR segment A onto OSMLR segment B "via" the turn channel will be reported.

**Comment by dnesbitt61** [comment]
This is being handled in the Reporter. When reporting a segment it will report the time starting the next segment rather than the time at the end of the current segment. Turn channels (and internal intersection edges and roundabout edges) are marked to allow connecting OSMLR segments on either side of the edge(s).

**Comment by drewda** [comment]
Related follow-up: https://github.com/opentraffic/reporter/issues/43
