### ISSUE TITLE
OSMLR segment migration process

### ISSUE THREAD

**Issue by drewda** [opentraffic/osmlr#7]
At present, the OSMLR build process assigns whatever IDs it sees fit to the segments it creates. This works well for one-off builds, but presents a problem when there is an installed base of Reporters using them to feed data back to the central hub as it requires us to handle version mismatches.

For example, if we versioned the IDs then the segment with ID `0/1/1` generated in 2017Q1 would be called `2017Q1:0/1/1` or similar (probably more efficiently bit-packed, but that's irrelevant to the point). This means that anyone slow to update to new data would be sending old IDs, which the central process would have to either translate to the new IDs or drop the data. Dropping the data is obviously bad, and translating might be non-trivial. At the very least, translating would require us to keep a translation table whose size would grow with the number of OSMLR data releases.

Instead, we propose to have a single ID "namespace", so that `0/1/1` would always refer to the same segment so long as that segment didn't change. This requires the OSMLR generation process to begin by matching the previous segment descriptors against the current data, and keeping the IDs for those which continue to match. Since OSMLR descriptors are designed to be tolerant to some kinds of changes, we anticipate that the majority will continue to match.

The few which do not match will result in the old IDs being marked as "deleted" or "superseded" and new IDs being allocated for the new segments (possibly with forward / back references to aid in translation).

This means that most of the Reporters which are tardy in updating to the latest data release will still be sending mostly useful data, and the data which still uses old IDs might be of a small enough volume to make translation feasible - if not in real time, then at least for batch historical analysis.

Goals of this task:

1. Integrate edge association into OSMLR generation, so that given a previous data file it will match edges to assign IDs first.
2. Any edges not associated should be marked deleted.
3. Any new edges or edges changed / split / combined so they do not match the old descriptors should be assigned IDs larger than any previously used in this tile.

**Comment by dnesbitt61** [comment]
Operationally - we store version and creation date within OSMLR tiles (both PBF and GeoJSON). May need or want to identify OSMLR tile version in reports so that Datastore can reject reports against deprecated OSMLR sets.  This may need some discussion. Basic premise is that we want to prohibit Reporters from sending data against old OSMLR data (with some grace period).

**Comment by dnesbitt61** [comment]
More details of the design and changes to OSMLR generation:

The OSMLR generation process will be updated to accept an optional OSMLR pbf directory - indicating that the OSMLR generation process should be based on the supplied OSMLR segment definitions. This will trigger the segment "migration" process rather than creating an initial or new set of OSMLR segments.

When updating or migrating OSMLR segments, the Valhalla data used by OSMLR generation must be "traffic-enabled". This means it must have OSMLR segment associations present in the Valhalla tiles (populated by running the valhalla_associate_segments process when creating Valhalla data). For new OSMLR segment generation the Valhalla tiles must not contain OSMLR segment associations. 

The OSMLR segment migration process essentially compares OSMLR segment definitions to Valhalla OSMLR association information to determine OSMLR segments that are still valid (have not changed significantly) and those that must be replaced. New segments are created both to replace OSMLR segments that have significant change as well as create new segments caused by new data (e.g. new roads).

The OSMLR segment migration process proceeds as follows:

- Iterate through OSMLR tiles (protocol buffer)
- Skip any deprecated OSMLR segments. (Write out to new OSMLR tile)
- Find current OSMLR segments that are no longer associated to Valhalla edges. Mark/identify these edges as deprecated/superseded since the underlying data has changed such that the OSMLR segment no longer matches the road network (within specific tolerances).
- Any existing OSMLR segments that are properly associated to Valhalla edges remain unchanged and are written out to the OSMLR protocol buffer tile. (OSMLR segments are immutable).
- OSMLR generation logic is run (as it is currently) to create new OSMLR segments. Any Valhalla edges that have valid OSMLR associations are not allowed during the creation of new OSMLR segments. This approach creates new segments to replace superseded OSMLR segments as well as new segments for newly added road data (e.g. new roads).

**Comment by dnesbitt61** [comment]
OSMLR segments are immutable. This means that as underlying data changes, as long as the roads match the OSMLR segments within specific "tolerances" the OSMLR segment remains valid. Properties of the OSMLR segment do NOT get updated. This decision has positives and negatives:

On the plus side this protects against a segment "drifting" through time such that each successive version matches (within tolerance) the prior version, but may not match earlier versions. 

On the negative side segment lengths can change slightly leading to slight inaccuracies in average speed computations of any data matched against the segment. 

By preserving matched segments, there is no provision to "merge" segments in cases where underlying data might be changed such that 2 adjoining segments can be merged (for example and intersecting road along the segment is deleted). This helps conserve Ids (rate of new Ids grows more slowly) and keeps previously associated data (without special update processing). However, in the case of short OSMLR segments it could be desirable to merge them into other segments where possible.

**Comment by drewda** [comment]
The initial implementation of the OSMLR update process is now complete:

- instructions on how to run the osmlr program to update an existing tileset are at https://github.com/opentraffic/osmlr#building-and-running
- a conceptual overview of the update process is at https://github.com/opentraffic/osmlr/blob/master/docs/osmlr_updates.md

Further work on tuning the update process will happen under #51
